---
deployment:
  tasks:
    - export DEPLOYPATH=/home/defianb6c2l6/public_html/FrostByte
    # Make sure the FrostByte folder exists, don't touch other files in public_html
    - mkdir -p $DEPLOYPATH
    # Sync contents of repo into FrostByte only, exclude .git + yaml itself
    - /bin/rsync -a --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH/
      # Ensure correct permissions for the FrostByte folder
    - /bin/chmod 755 /home/defianb6c2l6/public_html/FrostByte